# Generated by Django 3.1.7 on 2021-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_auto_20210324_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='timestamp_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
